import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('../datos/ventas.csv')
df['sales_date'] = pd.to_datetime(df['sales_date'])
df['mes'] = df['sales_date'].dt.to_period('M')
ventas_totales = df['sales_amount'].sum()
ventas_por_mes = df.groupby('mes')['sales_amount'].sum()
mes_mayor_venta = ventas_por_mes.idxmax()
print(f"Ventas totales: {ventas_totales}")
print(f"Mes con mayor venta: {mes_mayor_venta}")
print("\nVentas por mes:")
print(ventas_por_mes)
plt.figure(figsize=(12, 6))
plt.plot(ventas_por_mes.index.astype(str), ventas_por_mes.values, marker='o')
plt.title('Evolucion de Ventas Mensuales 2024')
plt.xlabel('Mes')
plt.ylabel('Ventas ($)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('../resultados/grafico_ventas.png')
print("Grafico guardado en /resultados/grafico_ventas.png")